/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_SBFakeBlur.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImageView, SBFWallpaperView;
@protocol _SBFakeBlurObserver;

__attribute__((visibility("hidden")))
@interface _SBFakeBlurView : XXUnknownSuperclass <_SBFakeBlur> {
	id<_SBFakeBlurObserver> _observer;
	int _requestedStyle;
	int _effectiveStyle;
	SBFWallpaperView* _wallpaperView;
	UIImageView* _imageView;
}
@property(assign, nonatomic) id<_SBFakeBlurObserver> observer;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) int variant;
+(id)_imageForStyle:(inout int*)style withSource:(id)source;
-(void)didMoveToWindow;
-(void)willMoveToWindow:(id)window;
-(void)layoutSubviews;
-(void)rotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)_setImage:(id)image style:(int)style notify:(BOOL)notify;
-(void)_updateImageWithSource:(id)source notifyObserver:(BOOL)observer;
-(void)updateImageWithSource:(id)source;
-(void)reconfigureWithSource:(id)source;
-(void)dealloc;
-(id)initWithVariant:(int)variant;
-(int)effectiveStyle;
-(void)requestStyle:(int)style;
@end

