/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBPushStoreObserver.h"
#import "BBRemoteDataProvider.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, BBDataProviderProxy, BBSectionInfo, NSObject, NSMutableArray;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface RLNDataProvider : XXUnknownSuperclass <SBPushStoreObserver, BBRemoteDataProvider> {
	NSString* _sectionID;
	NSMutableArray* _publisherBulletinIDs;
	BBSectionInfo* _defaultSectionInfo;
	NSString* _displayName;
	unsigned _pushSettings;
	BBDataProviderProxy* _proxy;
	NSObject<OS_dispatch_queue>* _queue;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) BBDataProviderProxy* proxy;
+(CGSize)_sizeFromSizeConstraint:(id)sizeConstraint originalSize:(CGSize)size;
-(void)pushStoreUserDeclinedDelivery;
-(void)pushStoreUserAcceptedDelivery;
-(void)_saveUpdatedSectionInfo;
-(void)pushStoreUpdatedPushSettings;
-(void)pushStoreClearedNotifications;
-(void)pushStoreNotificationsDidChange;
-(BOOL)syncsBulletinDismissal;
-(void)noteSectionInfoDidChange:(id)noteSectionInfo;
-(id)sectionIdentifier;
-(id)sortDescriptors;
-(id)clearedInfoForBulletins:(id)bulletins lastClearedInfo:(id)info;
-(id)clearedInfoAndBulletinsForClearingAllBulletinsWithLimit:(unsigned)limit lastClearedInfo:(id)info;
-(id)bulletinsFilteredBy:(unsigned)by count:(unsigned)count lastCleared:(id)cleared;
-(id)_allBulletinsWithLimit:(unsigned)limit;
-(void)_cleanupMigrationFromBrightonWithLastClearedDate:(id)lastClearedDate;
-(id)_latestBulletinInSet:(id)set;
-(unsigned)_bbActivationModeFromUIActivationMode:(unsigned)uiactivationMode;
-(id)_bbActionFromUIUserNotificationAction:(id)uiuserNotificationAction;
-(id)_actionsForCategoryIdentifier:(id)categoryIdentifier context:(unsigned)context;
-(id)_supplementaryActionsForPushStoreNotification:(id)pushStoreNotification context:(unsigned)context;
-(id)_defaultActionWithTitle:(id)title;
-(id)_bulletinForNotification:(id)notification;
-(id)_publisherBulletinIDForNotification:(id)notification;
-(id)sectionDisplayName;
-(id)defaultSectionInfo;
-(void)rebuildDefaultSectionInfoForPushSettings:(unsigned)pushSettings;
-(id)sectionParameters;
-(id)_sortKey;
-(BOOL)_isPushDataProvider;
-(void)invalidate;
-(void)_migrateSectionInfo;
-(void)dataProviderDidLoad;
-(void)dealloc;
-(id)initWithSectionID:(id)sectionID displayName:(id)name queue:(id)queue;
-(float)attachmentAspectRatioForRecordID:(id)recordID;
-(id)attachmentPNGDataForRecordID:(id)recordID sizeConstraints:(id)constraints;
-(id)_imageForRecordID:(id)recordID;
@end

