/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BSSettingDescriptionProvider.h"
#import "NSCopying.h"
#import "NSObject.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBActivationSettings.h"

@class NSString, BSMutableSettings;

@protocol SBActivationSettings <NSObject>
-(void)applyActivationSettings:(id)settings;
-(id)objectForActivationSetting:(unsigned)activationSetting;
-(void)setObject:(id)object forActivationSetting:(unsigned)activationSetting;
-(BOOL)boolForActivationSetting:(unsigned)activationSetting;
-(int)flagForActivationSetting:(unsigned)activationSetting;
-(void)setFlag:(int)flag forActivationSetting:(unsigned)activationSetting;
@end

__attribute__((visibility("hidden")))
@interface SBActivationSettings : XXUnknownSuperclass <BSSettingDescriptionProvider, SBActivationSettings, NSCopying> {
	BSMutableSettings* _settings;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(id)valueDescriptionForFlag:(int)flag object:(id)object ofSetting:(unsigned)setting;
-(id)keyDescriptionForSetting:(unsigned)setting;
-(id)basicDescriptionWithPrefix:(id)prefix;
-(void)applyActivationSettings:(id)settings;
-(id)objectForActivationSetting:(unsigned)activationSetting;
-(void)setObject:(id)object forActivationSetting:(unsigned)activationSetting;
-(BOOL)boolForActivationSetting:(unsigned)activationSetting;
-(int)flagForActivationSetting:(unsigned)activationSetting;
-(void)setFlag:(int)flag forActivationSetting:(unsigned)activationSetting;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

