/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertView.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBAlertViewAdapter : SBAlertView {
}
-(void)alertWindowViewControllerResizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame2;
-(void)setAlert:(id)alert;
-(id)alert;
@end

