/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAppSwitcherPageContentView.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, FBWindowContextHostManager, UIView, SBWallpaperEffectView;
@protocol FBWindowContextAppearance;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherContextHostWrapperView : XXUnknownSuperclass <SBAppSwitcherPageContentView> {
	FBWindowContextHostManager* _contextHostManager;
	UIView* _containerView;
	UIView<FBWindowContextAppearance>* _contextHostView;
	UIView* _snapshotView;
	SBWallpaperEffectView* _wallpaperEffectView;
	int _orientation;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int orientation;
-(void)_viewDidAnimatePresentation:(id)_view;
-(void)_viewDidAnimateDismissal:(id)_view;
-(void)_viewDismissing:(id)dismissing;
-(void)_viewPresenting:(id)presenting;
-(CGAffineTransform)_rotationTransformForOrientation:(int)orientation;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)didMoveToSuperview;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame application:(id)application;
-(id)initWithFrame:(CGRect)frame;
@end

