/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherRemoteAlertSet : XXUnknownSuperclass <NSCopying> {
	NSMutableArray* _alerts;
	NSMutableSet* _placeholderIdentifiers;
}
-(id)placeholderDisplayItems;
-(id)placeholderBundleIdentifiers;
-(id)displayItems;
-(id)serviceBundleIdentifiers;
-(id)alertForDisplayLayout:(id)displayLayout;
-(id)alertForBundleIdentifier:(id)bundleIdentifier;
-(id)alertAtIndex:(unsigned)index;
-(BOOL)containsAlert:(id)alert;
-(unsigned)count;
-(void)removePlaceholderForIdentifier:(id)identifier;
-(void)addPlaceholderForIdentifier:(id)identifier;
-(void)removeRemoteAlert:(id)alert;
-(void)addRemoteAlert:(id)alert;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithAlertSet:(id)alertSet zone:(NSZone*)zone;
@end

