/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDate, NSArray;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherPeopleContactItem : XXUnknownSuperclass <NSCopying> {
	NSString* _name;
	unsigned _nameFormatHash;
	NSArray* _contactActions;
	int _personRecordID;
	NSDate* _recordLastUpdatedDate;
}
@property(copy, nonatomic) NSDate* recordLastUpdatedDate;
@property(copy, nonatomic) NSArray* contactActions;
@property(readonly, assign, nonatomic) int personRecordID;
@property(assign, nonatomic) unsigned nameFormatHash;
@property(copy, nonatomic) NSString* name;
-(BOOL)hasFaceTimeAudioAction;
-(BOOL)hasFaceTimeAction;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)description;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithName:(id)name nameFormatHash:(unsigned)hash abRecordID:(int)anId lastUpdated:(id)updated contactActions:(id)actions;
@end

