/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBTestRecipe.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBBiometricEventsTestRecipe : XXUnknownSuperclass <SBTestRecipe> {
	unsigned _eventIndex;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned eventIndex;
+(id)title;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)postEvent:(unsigned)event;
@end

