/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDefaultBannerViewSource.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, BBBulletin, UIImage, SBUISound, NSArray, BBObserver;

__attribute__((visibility("hidden")))
@interface SBBulletinBannerItem : XXUnknownSuperclass <SBDefaultBannerViewSource> {
	BBBulletin* _seedBulletin;
	BBObserver* _observer;
	NSArray* _additionalBulletins;
	UIImage* _iconImage;
	SBUISound* _sound;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)itemWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
+(id)itemWithBulletin:(id)bulletin andObserver:(id)observer;
-(BOOL)overridesQuietMode;
-(BOOL)isCritical;
-(BOOL)inertWhenLocked;
-(BOOL)showMessagePreview;
-(id)attachmentImage;
-(id)attachmentText;
-(id)iconImage;
-(id)sourceDate;
-(id)_seedBulletinMessage;
-(id)suppressedMessage;
-(id)message;
-(id)subtitle;
-(id)title;
-(id)actionWithIdentifier:(id)identifier;
-(BOOL)_supportsSubActions;
-(id)lockScreenActionContextWithContext:(id)context;
-(id)_defaultBBAction;
-(id)defaultActionWithContext:(id)context;
-(id)subActions;
-(id)subActionLabels;
-(id)pullDownNotification;
-(BOOL)canShowInAssistant;
-(id)sortDate;
-(id)seedBulletin;
-(id)_uiBannerActionForBBAction:(id)bbaction context:(id)context;
-(id)action;
-(id)sound;
-(void)_setSound;
-(id)accessoryIconMask;
-(id)additionalBulletins;
-(void)dealloc;
-(id)_initWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
@end

