/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBCarBannerNotificationView : XXUnknownSuperclass {
}
-(void)setFrame:(CGRect)frame;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

