/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWindowLayoutStrategy.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol SBStarkSessionConfiguring;

__attribute__((visibility("hidden")))
@interface SBCarWindowLayoutStrategy : XXUnknownSuperclass <SBWindowLayoutStrategy> {
	id<SBStarkSessionConfiguring> _configuration;
	unsigned _layout;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)strategyWithConfiguration:(id)configuration layout:(unsigned)layout;
+(UIEdgeInsets)statusBarEdgeInsetsForConfiguration:(id)configuration;
-(BOOL)_isLayoutBoundsOnly;
-(int)jailBehavior;
-(CGRect)frameForWindow:(id)window;
-(void)dealloc;
-(id)initWithConfiguration:(id)configuration layout:(unsigned)layout;
@end

