/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSceneLayoutManager.h"
#import "SpringBoard-Structs.h"

@protocol SBStarkSessionConfiguring;

__attribute__((visibility("hidden")))
@interface SBCarDisplaySceneLayoutManager : SBSceneLayoutManager {
	id<SBStarkSessionConfiguring> _configuration;
}
-(CGRect)frameForDisplayItem:(id)displayItem inLayout:(id)layout;
-(void)dealloc;
-(id)initWithManager:(id)manager configuration:(id)configuration;
@end

