/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIControlCenterButtonDelegate.h"
#import "SBCCButtonModuleDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIAlertController, SBCCButtonModule;
@protocol SBCCButtonControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBCCButtonController : XXUnknownSuperclass <SBCCButtonModuleDelegate, SBUIControlCenterButtonDelegate> {
	UIAlertController* _alertController;
	id<SBCCButtonControllerDelegate> _delegate;
	SBCCButtonModule* _module;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SBCCButtonModule* module;
@property(retain, nonatomic) id<SBCCButtonControllerDelegate> delegate;
-(void)buttonModulePropertiesDidChange:(id)buttonModuleProperties;
-(void)buttonModuleStateDidChange:(id)buttonModuleState;
-(void)_buttonTapped;
-(void)buttonTapped:(id)tapped;
-(BOOL)presentConfirmationAlert;
-(id)glyphImageForState:(int)state;
-(void)_updateButtonProperties;
-(void)_updateButtonState;
-(void)controlCenterDidDismiss;
-(void)viewDidLoad;
-(id)view;
-(void)dealloc;
-(id)initWithModule:(id)module;
@end

