/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"
#import "SBStateSettings.h"
#import "SBDeactivationSettings.h"
#import "SBActivationSettings.h"


@protocol SBDisplayProtocol <NSObject, SBActivationSettings, SBDeactivationSettings, SBStateSettings>
-(void)clearStateSettings;
-(void)clearDeactivationSettings;
-(void)clearActivationSettings;
-(id)copyDisplaySettings;
-(void)deactivate;
-(void)activate;
-(BOOL)suppressesControlCenter;
-(BOOL)suppressesNotificationCenter;
-(BOOL)suppressesBanners;
-(BOOL)allowsEventOnlySuspension;
-(id)effectiveStatusBarStyleRequest;
-(id)statusBarStyleRequest;
-(int)starkStatusBarStyle;
-(int)statusBarStyle;
@end

