/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBFolderBackgroundView;

__attribute__((visibility("hidden")))
@interface SBFloatyFolderBackgroundClipView : XXUnknownSuperclass {
	SBFolderBackgroundView* _backgroundView;
}
@property(readonly, assign, nonatomic) SBFolderBackgroundView* backgroundView;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

