/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"
#import "SpringBoard-Structs.h"


@protocol SBFolderControllerDelegate <NSObject>
-(void)folderControllerDidEndScrolling:(id)folderController;
-(void)folderControllerShouldBeginEditing:(id)folderController;
-(void)folderControllerShouldClose:(id)folderController;
-(void)folderController:(id)controller draggedIconShouldDropFromListView:(id)draggedIcon;
-(BOOL)folderController:(id)controller draggedIconMightDropFromListView:(id)listView;
-(BOOL)folderController:(id)controller draggedIconDidMoveFromListView:(id)draggedIcon toListView:(id)listView;
-(BOOL)folderController:(id)controller draggedIconDidPauseAtLocation:(CGPoint)draggedIcon inListView:(id)listView;
-(Class)controllerClassForFolder:(id)folder;
@optional
-(void)folderControllerDidReceiveCancelReachabilityAction:(id)folderController;
@end

