/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBReusableViewMap.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBIconLabelAccessoryViewMap : SBReusableViewMap {
}
+(CGSize)labelAccessoryViewSizeForType:(int)type;
+(id)homescreenMap;
-(id)viewForLabelAccessoryType:(int)labelAccessoryType;
@end

