/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewController.h"
#import "SBLockOverlayViewDelegate.h"

@class NSString, SBAwayBulletinListItem, SBLockOverlayView;

__attribute__((visibility("hidden")))
@interface SBLockScreenFullscreenBulletinViewController : SBLockOverlayViewController <SBLockOverlayViewDelegate> {
	SBLockOverlayView* _bulletinView;
	BOOL _performedAction;
	SBAwayBulletinListItem* _bulletinItem;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SBAwayBulletinListItem* bulletinItem;
-(BOOL)isPlayingSound;
-(id)_lockScreenActionContext;
-(id)slideToUnlockText;
-(void)performUnlockAction;
-(void)performSnoozeAction;
-(id)_snoozeAction;
-(BOOL)_hasSnoozeAction;
-(id)_dismissAction;
-(void)performDismissAction;
-(id)_alternateAction;
-(BOOL)_hasAlternateAction;
-(void)performAlternateAction;
-(void)performAction:(id)action;
-(id)_titleForAlternateActionButton;
-(id)_calculatedTitleForAlternateActionButton;
-(id)_customTitleForAlternateActionButton;
-(void)handleTapGestureFromView:(id)view;
-(void)lockButtonPressed:(id)pressed;
-(BOOL)handleVolumeButtonPressed;
-(BOOL)handleVolumeUpButtonPressed;
-(BOOL)handleVolumeDownButtonPressed;
-(void)volumeChanged:(id)changed;
-(void)updateContent;
-(void)viewDidAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

