/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertWindowViewController.h"


__attribute__((visibility("hidden")))
@interface SBMainScreenAlertWindowViewController : SBAlertWindowViewController {
}
-(void)_getRotationContentSettings:(XXStruct_ykCi7C*)settings;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)noteAlertWindow:(id)window didDisplayAlert:(id)alert;
-(BOOL)alertWindow:(id)window canAnimateInAlert:(id)alert;
@end

