/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIStatusBarStateObserver.h"
#import "SBStatusBarStateProvider.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBMainStatusBarStateProvider : SBStatusBarStateProvider <UIStatusBarStateObserver> {
	BOOL _overridePercent;
	BOOL _killActivity;
	BOOL _itemIsDisabled[26];
	BOOL _itemWasDisabled[26];
	BOOL _timeEnabled;
	BOOL _timeCloaked;
	BOOL _allButBatteryCloaked;
	BOOL _telephonyAndBluetoothCloaked;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstance;
-(void)statusBarStateProvider:(id)provider didPostStatusBarData:(const XXStruct_gly1hD*)data withActions:(int)actions;
-(void)_composePostDataFromAggregatorData:(XXStruct_gly1hD*)aggregatorData;
-(BOOL)_shouldPostForVisitedItem:(int)visitedItem withUpdates:(BOOL)updates toAggregatorData:(const XXStruct_gly1hD*)aggregatorData;
-(void)setTelephonyAndBluetoothItemsCloaked:(BOOL)cloaked;
-(void)setAllItemsExceptBatteryCloaked:(BOOL)cloaked;
-(void)setTimeCloaked:(BOOL)cloaked;
-(void)enableTime:(BOOL)time crossfade:(BOOL)crossfade crossfadeDuration:(double)duration;
-(void)enableTime:(BOOL)time;
-(BOOL)isTimeEnabled;
-(void)_updateDisabledItems;
-(void)dealloc;
-(id)init;
@end

