/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSceneManager.h"


__attribute__((visibility("hidden")))
@interface SBMainDisplaySceneManager : SBSceneManager {
}
-(id)layoutManager;
-(id)_newLayoutManager;
@end

