/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBTestRecipe.h"
#import "SBThermalWarningAlertItemDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SBAlertItem;

__attribute__((visibility("hidden")))
@interface SBOmnibusAlertItemTestRecipe : XXUnknownSuperclass <SBThermalWarningAlertItemDelegate, SBTestRecipe> {
	SBAlertItem* _item;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)title;
-(id)_nextAlertItemToTest;
-(id)_mapsApp;
-(id)_anySUDescriptor;
-(id)_anyIcon;
-(void)thermalWarningAlert:(id)alert didTriggerAction:(int)action;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)_dismissCurrentItem;
@end

