/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_MKPlaceViewControllerFeedbackDelegate.h"
#import "SBSearchResultsModalViewControllerAction.h"

@class NSString, MKMapItem;

__attribute__((visibility("hidden")))
@interface SBSearchResultsMapsAction : SBSearchResultsModalViewControllerAction <_MKPlaceViewControllerFeedbackDelegate> {
	MKMapItem* _mapItem;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) MKMapItem* mapItem;
-(void)performButtonAction;
-(id)buttonActionTitle;
-(void)placeViewController:(id)controller shouldLogFeedbackOfType:(int)type;
-(void)loadModalViewControllerWithCompletionBlock:(id)completionBlock;
-(void)dealloc;
@end

