/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UITextView, UILabel;

__attribute__((visibility("hidden")))
@interface SBSearchWikiRowCell : XXUnknownSuperclass {
	UILabel* _labelLabel;
	UITextView* _valueTextView;
}
@property(assign) UITextView* valueTextView;
@property(assign) UILabel* labelLabel;
-(void)layoutSubviews;
-(CGSize)systemLayoutSizeFittingSize:(CGSize)size withHorizontalFittingPriority:(float)horizontalFittingPriority verticalFittingPriority:(float)priority;
-(void)awakeFromNib;
@end

