/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSearchResultDetailsViewController.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SPSearchResultSection, SPSearchResult, UIColor;
@protocol SBSearchResultDetailsViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBSearchWikipediaViewController : XXUnknownSuperclass <SBSearchResultDetailsViewController> {
	id<SBSearchResultDetailsViewControllerDelegate> actionDelegate;
	UIColor* _contentBackgroundColor;
	SPSearchResult* _result;
	SPSearchResultSection* _section;
}
@property(retain) UIColor* contentBackgroundColor;
@property(readonly, assign) BOOL wantsInset;
@property(assign) id<SBSearchResultDetailsViewControllerDelegate> actionDelegate;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain) SPSearchResultSection* section;
@property(retain) SPSearchResult* result;
+(id)viewControllerForResult:(id)result inSection:(id)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view shouldHighlightRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)loadWithCompletionBlock:(id)completionBlock;
-(void)reloadData;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)dealloc;
@end

