/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "SBSearchHeaderDelegate.h"
#import "SBReachabilityObserver.h"
#import "UINavigationControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "SBSearchResultsActionManagerDelegate.h"
#import "SBUIActiveOrientationObserver.h"
#import "UISearchBarDelegate.h"
#import "SBSearchGestureObserver.h"
#import "UITextFieldDelegate.h"
#import "SpringBoard-Structs.h"
#import "SPSearchAgentDelegate.h"
#import "UITableViewDataSource.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIGestureRecognizer, SBSearchFirstTimeViewController, UIPanGestureRecognizer, UITapGestureRecognizer, UIWindow, UITableView, UIViewController, UINavigationController, UILabel, SBSearchResultsActionManager, SBSearchHeader, SBSearchResultsBackdropView;

__attribute__((visibility("hidden")))
@interface SBSearchViewController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource, SPSearchAgentDelegate, SBSearchGestureObserver, UISearchBarDelegate, SBSearchResultsActionManagerDelegate, UIGestureRecognizerDelegate, UINavigationControllerDelegate, SBUIActiveOrientationObserver, SBReachabilityObserver, UITextFieldDelegate, SBSearchHeaderDelegate> {
	UINavigationController* _navigationController;
	UIViewController* _mainViewController;
	SBSearchFirstTimeViewController* _firstTimeViewController;
	UITableView* _tableView;
	SBSearchHeader* _searchHeader;
	SBSearchResultsBackdropView* _tableBackdrop;
	SBSearchResultsActionManager* _actionManager;
	UIWindow* _presentingWindow;
	int _presentingWindowOrientation;
	UILabel* _noResultsLabel;
	UITapGestureRecognizer* _tapRecognizer;
	UIPanGestureRecognizer* _panRecognizer;
	void* _addressBook;
	float _lastContentOffsetY;
	BOOL _scrollDown;
	int _visibility;
	float _headerHeight;
	BOOL _hasShownBackgroundSinceLastClear;
	int _firstTimeViewShowCount;
	BOOL _canShowFirstTimeView;
	double _triggerTimestamp;
	CGPoint _preReachabilityTableViewOrigin;
	CGPoint _reachabilityTableViewOrigin;
	BOOL _showingForReachability;
	UIGestureRecognizer* _cancelRecognizer;
	id _fadeOutCompletionBlock;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic, getter=isVisible) BOOL visible;
@property(readonly, assign, nonatomic, getter=isFadingOut) BOOL fadingOut;
+(id)sharedInstance;
-(void)handleCancelReachabilityGesture:(id)gesture;
-(void)handleReachabilityModeDeactivated;
-(void)handleReachabilityModeActivated;
-(void)_animateForReachabilityDeactivatedWithHandler:(id)handler;
-(void)_animateForReachabilityActivatedWithHandler:(id)handler;
-(void)_performReachabilityTransactionForActivate:(BOOL)activate immediately:(BOOL)immediately;
-(void)_lockScreenUIWillLock:(id)_lockScreenUI;
-(void)activeInterfaceOrientationDidChangeToOrientation:(int)activeInterfaceOrientation willAnimateWithDuration:(double)duration fromOrientation:(int)orientation;
-(void)activeInterfaceOrientationWillChangeToOrientation:(int)activeInterfaceOrientation;
-(void)_rotatePresentingWindowIfNecessaryTo:(int)to withDuration:(double)duration;
-(void)navigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)actionManager:(id)manager sendFeedback:(id)feedback;
-(UIEdgeInsets)actionManagerDetailsViewEdgeInsets:(id)insets;
-(void)actionManager:(id)manager dismissViewController:(id)controller completion:(id)completion animated:(BOOL)animated;
-(void)actionManager:(id)manager presentViewController:(id)controller completion:(id)completion modally:(BOOL)modally;
-(void)actionManager:(id)manager dismissAnimated:(BOOL)animated completionBlock:(id)block;
-(void)cancelButtonPressed;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)viewWillAppear:(BOOL)view;
-(void)scrollViewDidScroll:(id)scrollView;
-(BOOL)textFieldShouldClear:(id)textField;
-(void)_searchFieldReturnPressed;
-(void)_searchFieldEditingChanged;
-(void)searchGesture:(id)gesture completedShowing:(BOOL)showing;
-(void)searchGesture:(id)gesture changedPercentComplete:(float)complete;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view estimatedHeightForHeaderInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didUnhighlightRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didHighlightRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)_updateCellClipping:(id)clipping;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)searchAgentClearedResults:(id)results;
-(void)searchAgentUpdatedResults:(id)results;
-(void)_contentSizeCategoryDidChange:(id)_contentSizeCategory;
-(void)_keyboardWillChangeFrame:(id)_keyboard;
-(void)_handlePanRecognizer:(id)recognizer;
-(void)_handleTapRecognizer:(id)recognizer;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)_handleDismissGesture;
-(void)_sendAbandonmentFeedbackForReason:(unsigned)reason;
-(void)_fadeOutAndHideKeyboardAnimated:(BOOL)animated completionBlock:(id)block;
-(void)_fadeForLaunchWithDuration:(double)duration completion:(id)completion;
-(void)attributionButtonTapped:(id)tapped;
-(void)_sendFeedback:(id)feedback;
-(void)_updateClipping;
-(void)_updateHeaderHeightIfNeeded;
-(void)_deselectTableViewCell;
-(id)_actionManager;
-(void)_updateTableContents;
-(void)_setFirstTimeViewVisible:(BOOL)visible;
-(BOOL)_showFirstTimeView;
-(BOOL)_hasNoResultsForQuery;
-(BOOL)_hasResults;
-(BOOL)_hasNoQuery;
-(BOOL)_showingKeyboard;
-(void)_setShowingKeyboard:(BOOL)keyboard;
-(void)_setVisibility:(int)visibility;
-(void)dismissAnimated:(BOOL)animated completionBlock:(id)block;
-(void)dismiss;
-(void)viewDidLayoutSubviews;
-(void)traitCollectionDidChange:(id)traitCollection;
-(UIEdgeInsets)searchBorderMarginsForSearchField:(BOOL)searchField cancelMargins:(UIEdgeInsets*)margins;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

