/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBSIMLockEntryAlert : SBAlert {
	int _status;
}
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)supportedInterfaceOrientations;
-(int)interfaceOrientationForActivation;
-(BOOL)_forcesPortraitOrientation;
-(void)deactivate;
-(void)activate;
-(int)status;
-(id)lockEntryView;
-(BOOL)hasTranslucentBackground;
-(id)alertDisplayViewWithSize:(CGSize)size;
@end

