/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolderController.h"

@class NSIndexPath, SBIcon;

__attribute__((visibility("hidden")))
@interface SBStarkFolderController : SBFolderController {
	NSIndexPath* _focusedIndex;
	unsigned _interactionAffordances;
	BOOL _supportsKnobEvents;
	BOOL _supportsTouchEvents;
}
@property(retain, nonatomic) SBIcon* focusedIcon;
@property(retain, nonatomic) NSIndexPath* focusedIndex;
@property(assign, nonatomic) unsigned interactionAffordances;
-(void)folderView:(id)view currentPageIndexDidChange:(int)currentPageIndex;
-(void)_setFocusedIndex:(id)index animated:(BOOL)animated scrollToPageIfNecessary:(BOOL)pageIfNecessary;
-(void)setInnerFolderController:(id)controller;
-(void)handleFocusMoveAlongHeading:(unsigned)heading;
-(void)setFocusedIndex:(id)index animated:(BOOL)animated;
-(id)_iconPageIndicatorImageSetCache;
-(Class)_contentViewClass;
-(void)dealloc;
-(id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map context:(id)context;
@end

