/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkScreenControllerDelegate.h"
#import "SBScreenConnectionHandler.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SBStarkScreenController, NSHashTable, SBSStatusBarStyleOverridesAssertion, SBPasscodeLockDisableAssertion, SBSpuriousScreenUndimmingAssertion, SBStarkStatusBarStateProvider, SBLockScreenDisableAssertion, NSMapTable;

__attribute__((visibility("hidden")))
@interface SBStarkScreenManager : XXUnknownSuperclass <SBScreenConnectionHandler, SBStarkScreenControllerDelegate> {
	NSMapTable* _screenToControllerMap;
	NSHashTable* _observers;
	SBStarkScreenController* _currentScreenController;
	SBStarkStatusBarStateProvider* _statusBarStateProvider;
	SBSpuriousScreenUndimmingAssertion* _spuriousScreenUndimmingAssertion;
	SBPasscodeLockDisableAssertion* _deviceLockDisableAssertion;
	SBLockScreenDisableAssertion* _lockScreenDisableAssertion;
	SBPasscodeLockDisableAssertion* _earlyConnectDeviceLockDisableAssertion;
	SBSStatusBarStyleOverridesAssertion* _carPlayStatusBarStyleOverrideAssertion;
	SBSStatusBarStyleOverridesAssertion* _earlyCarPlayStatusBarStyleOverrideAssertion;
	BOOL _hasShownConnectedAlert;
	BOOL _delayShowingConnectedAlert;
	BOOL _geoSupported;
	BOOL _earlyStarkConnection;
	BOOL _delayUpdatingLockOutMode;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstance;
-(void)screenManager:(id)manager didTriggerConnectionHandlerEvent:(int)event forScreen:(id)screen;
-(BOOL)screenManager:(id)manager shouldBindConnectionHandlerToScreen:(id)screen;
-(void)starkScreenControllerWantsRelockUI:(id)ui;
-(BOOL)starkScreenControllerShouldDelayUpdateLockoutMode:(id)starkScreenController;
-(void)_promptConnectionSteps;
-(void)_clearPromptState;
-(void)_clearEarlyConnectState;
-(void)_clearEarlyConnectStateTimerExpired;
-(void)_unscheduleClearEarlyConnectStateExpirationTimer;
-(void)_scheduleClearEarlyConnectStateExpirationTimer;
-(void)_earlyStarkConnection;
-(void)_usbStarkConnected;
-(void)_setCurrentController:(id)controller;
-(void)_updateGeoSupport;
-(BOOL)shouldShowCarPlayStatusBarItem;
-(id)screenControllerForScreen:(id)screen;
-(id)screenControllerForDisplay:(id)display;
-(BOOL)promptRelockUIIfAppropriate;
-(BOOL)handleUnlockAttempt;
-(void)prepareToHandleUnlockAttempt;
-(BOOL)isGeoSupported;
-(id)statusBarStateProvider;
-(BOOL)isStarkActive;
-(id)activeScreenController;
-(BOOL)starkScreenIsAttached;
-(id)currentScreenController;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(void)dealloc;
-(id)init;
@end

