/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkBannerItem.h"

@class BBBulletin, SBUISound;

__attribute__((visibility("hidden")))
@interface SBStarkBulletinBannerItem : SBStarkBannerItem {
	BBBulletin* _bulletin;
	SBUISound* _sound;
	unsigned _feed;
}
-(id)_uiBannerActionForBBAction:(id)bbaction context:(id)context;
-(BOOL)_supportsSubActions;
-(id)subActions;
-(id)subActionLabels;
-(BOOL)shouldShowModalSubActions;
-(id)bbAllActions;
-(id)bbSupplementaryActions;
-(id)_bbDismissAppearance;
-(id)_bbDismissAction;
-(id)sound;
-(id)sourceDate;
-(id)action;
-(BOOL)matchesContext:(id)context;
-(int)defaultActionType;
-(id)categoryImage;
-(id)message;
-(id)subTitle;
-(id)title;
-(void)updateBulletinToInstance:(id)instance;
-(void)dealloc;
-(id)initWithBulletin:(id)bulletin feed:(unsigned)feed;
@end

