/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkSessionConfiguring.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIScreen, AVExternalDevice, NSSet, UITraitCollection;

__attribute__((visibility("hidden")))
@interface SBStarkSessionConfiguration : XXUnknownSuperclass <SBStarkSessionConfiguring> {
	AVExternalDevice* _device;
	unsigned _interactionAffordances;
	int _layoutJustification;
	UIScreen* _screen;
	UITraitCollection* _traitCollection;
	BOOL _geoSupported;
	NSSet* _protocols;
}
@property(readonly, copy, nonatomic) UITraitCollection* traitCollection;
@property(readonly, retain, nonatomic) UIScreen* screen;
@property(readonly, assign, nonatomic) int layoutJustification;
@property(readonly, assign, nonatomic) unsigned interactionAffordances;
@property(readonly, retain, nonatomic) AVExternalDevice* device;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSSet* sessionProtocols;
@property(assign, nonatomic, getter=isGeoSupported) BOOL geoSupported;
-(void)dealloc;
-(id)initWithDevice:(id)device screen:(id)screen;
@end

