/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIScreen, BSZeroingWeakReference, NSMutableArray, SBStarkScreenFocusAssertion;

__attribute__((visibility("hidden")))
@interface SBStarkScreenFocusController : XXUnknownSuperclass {
	UIScreen* _screen;
	NSString* _displayID;
	NSMutableArray* _assertions;
	SBStarkScreenFocusAssertion* _lastFocusAssertion;
	BSZeroingWeakReference* _weak_lastFocusWindow;
}
-(id)description;
-(id)focusWindow;
-(void)dropReason:(id)reason;
-(void)takeWithPriority:(float)priority reason:(id)reason forWindow:(id)window bundleIdentifier:(id)identifier pid:(int)pid;
-(void)invalidate;
-(void)_applyAssertion:(id)assertion;
-(void)_updateEventFocus;
-(void)dealloc;
-(id)initWithScreen:(id)screen;
@end

