/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BSSettingDescriptionProvider.h"
#import "NSCopying.h"
#import "NSObject.h"
#import "SBStateSettings.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, BSMutableSettings;

@protocol SBStateSettings <NSObject>
-(void)applyStateSettings:(id)settings;
-(id)objectForStateSetting:(unsigned)stateSetting;
-(void)setObject:(id)object forStateSetting:(unsigned)stateSetting;
-(BOOL)boolForStateSetting:(unsigned)stateSetting;
-(int)flagForStateSetting:(unsigned)stateSetting;
-(void)setFlag:(int)flag forStateSetting:(unsigned)stateSetting;
@end

__attribute__((visibility("hidden")))
@interface SBStateSettings : XXUnknownSuperclass <BSSettingDescriptionProvider, SBStateSettings, NSCopying> {
	BSMutableSettings* _settings;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(id)valueDescriptionForFlag:(int)flag object:(id)object ofSetting:(unsigned)setting;
-(id)keyDescriptionForSetting:(unsigned)setting;
-(id)basicDescriptionWithPrefix:(id)prefix;
-(void)applyStateSettings:(id)settings;
-(id)objectForStateSetting:(unsigned)stateSetting;
-(void)setObject:(id)object forStateSetting:(unsigned)stateSetting;
-(BOOL)boolForStateSetting:(unsigned)stateSetting;
-(int)flagForStateSetting:(unsigned)stateSetting;
-(void)setFlag:(int)flag forStateSetting:(unsigned)stateSetting;
-(id)processSettings;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

