/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBStarkScreenManagerObserver.h"
#import "SBStatusBarStateProvider.h"

@class NSString, NSDateFormatter;

__attribute__((visibility("hidden")))
@interface SBStarkStatusBarStateProvider : SBStatusBarStateProvider <SBStarkScreenManagerObserver> {
	BOOL _oldAggregatorTimeCString[64];
	BOOL _timeCString[64];
	NSDateFormatter* _timeFormatter;
	BOOL _showOptimalCellData;
	BOOL _disableBattery;
	int _deviceTransportType;
	NSString* _inCallDetail;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(BOOL)_itemIsIgnored:(int)ignored;
-(void)_callDurationChanged;
-(void)_resetTimeItemFormatter;
-(void)starkScreenManagerDidChangeActiveController:(id)starkScreenManager;
-(id)_timeFormatter;
-(void)_composePostDataFromAggregatorData:(XXStruct_gly1hD*)aggregatorData;
-(BOOL)_shouldPostForUpdatesToNonItemData:(const XXStruct_gly1hD*)nonItemData;
-(BOOL)_shouldPostForVisitedItem:(int)visitedItem withUpdates:(BOOL)updates toAggregatorData:(const XXStruct_gly1hD*)aggregatorData;
-(id)doubleHeightStatusStringForStyle:(int)style;
-(void)dealloc;
-(id)init;
@end

