/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class UIScreen, AVExternalDevice, NSSet, UITraitCollection;

@protocol SBStarkSessionConfiguring <NSObject>
@property(readonly, copy, nonatomic) NSSet* sessionProtocols;
@property(readonly, assign, nonatomic, getter=isGeoSupported) BOOL geoSupported;
@property(readonly, copy, nonatomic) UITraitCollection* traitCollection;
@property(readonly, retain, nonatomic) UIScreen* screen;
@property(readonly, assign, nonatomic) int layoutJustification;
@property(readonly, assign, nonatomic) unsigned interactionAffordances;
@property(readonly, retain, nonatomic) AVExternalDevice* device;
@end

