/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconBadgeView.h"


__attribute__((visibility("hidden")))
@interface SBStarkIconBadgeView : SBIconBadgeView {
}
+(id)_checkoutBackgroundImage;
+(float)_textPadding;
+(float)_maxTextWidth;
+(id)_textFont;
@end

