/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListPageControl.h"


__attribute__((visibility("hidden")))
@interface SBStarkIconListPageControl : SBIconListPageControl {
	float _scale;
}
@property(assign, nonatomic) float scale;
-(float)_indicatorSpacing;
-(id)_iconListIndicatorImage:(BOOL)image;
@end

