/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIStatusBarStyleDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIView, NSMutableSet, UIStatusBar;
@protocol SBStarkSessionConfiguring;

__attribute__((visibility("hidden")))
@interface SBStarkStatusBarViewController : XXUnknownSuperclass <UIStatusBarStyleDelegate> {
	id<SBStarkSessionConfiguring> _configuration;
	UIStatusBar* _statusBarView;
	id<UIStatusBarStyleDelegate> _statusBarStyleDelegate;
	NSMutableSet* _statusBarHideReasons;
	int _requestedStyle;
	BOOL _styleHasBeenRequested;
	float _statusBarWidth;
	UIView* _separatorView;
	BOOL _separatorHidden;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isSeparatorHidden) BOOL separatorHidden;
@property(assign, nonatomic) id<UIStatusBarStyleDelegate> statusBarStyleDelegate;
-(void)statusBar:(id)bar didTriggerButtonType:(int)type withAction:(int)action;
-(void)statusBar:(id)bar didAnimateFromHeight:(float)height toHeight:(float)height3 animation:(int)animation;
-(void)statusBar:(id)bar willAnimateFromHeight:(float)height toHeight:(float)height3 duration:(double)duration animation:(int)animation;
-(int)statusBar:(id)bar styleForRequestedStyle:(int)requestedStyle overrides:(int)overrides;
-(BOOL)_isStatusBarHidden;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)_layoutStatusBar:(id)bar;
-(id)newFakeStatusBarWithStyle:(int)style;
-(id)newFakeStatusBar;
-(void)updateStatusBarWithRequestedStyle:(int)requestedStyle animationFactory:(id)factory;
-(void)setStatusBarHidden:(BOOL)hidden forReason:(id)reason withAnimationFactory:(id)animationFactory;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithConfiguration:(id)configuration;
@end

