/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class FBWindowContextHostManager, SBAppSwitcherPageView, UIView, SBAppSwitcherController, SBDisplayLayout;

__attribute__((visibility("hidden")))
@interface SBUISwitcherDismissAnimationController : SBUIMainScreenAnimationController {
	SBAppSwitcherController* _switcherController;
	UIView* _appContextHostView;
	FBWindowContextHostManager* _contextHostManager;
	SBAppSwitcherPageView* _animatingPageView;
	SBDisplayLayout* _activatingDisplayLayout;
	BOOL _finishedSwitcherAnimation;
	BOOL _finishedCrossfadingToHostView;
}
-(void)_reportAnimationFinishedIfNecessary;
-(void)_noteCrossfadeDidFinish;
-(void)_noteSwitcherAnimationFinished;
-(void)_crossfadeApp;
-(void)_evaluateDependenciesForCrossfadeStart;
-(void)_applicationDependencyStateChanged;
-(id)_animationProgressDependency;
-(BOOL)_isActivatingFromContinuityApp;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp deactivatingApp:(id)app;
-(id)initWithActivatingApp:(id)activatingApp activatingDisplayLayout:(id)layout deactivatingApp:(id)app;
@end

