/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBUIRemoteAlertServiceInterface
@optional
-(void)setUserInfo:(id)info;
-(void)noteActivatedForCustomReason:(id)customReason;
-(void)noteActivatedForActivityContinuationWithIdentifier:(id)identifier;
-(void)handleDoubleHeightStatusBarTap;
-(void)handleHeadsetButtonPressed:(BOOL)pressed;
-(void)handleVolumeDownButtonPressed;
-(void)handleVolumeUpButtonPressed;
-(void)handleLockButtonPressed;
-(void)handleHomeButtonPressed;
@end

