/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class SBAlert, SBLockScreenViewController, SBAlertManager;

__attribute__((visibility("hidden")))
@interface SBUIAnimationFadeAlertToLockscreen : SBUIMainScreenAnimationController {
	SBLockScreenViewController* _lockScreenViewController;
	SBAlert* _deactivatingAlert;
	SBAlertManager* _alertManager;
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(double)animationDelay;
-(double)animationDuration;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithLockScreenController:(id)lockScreenController deactivatingAlert:(id)alert alertManager:(id)manager;
@end

