/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol UIStatusBarStateObserver <NSObject>
-(void)statusBarStateProvider:(id)provider didPostStatusBarData:(const XXStruct_gly1hD*)data withActions:(int)actions;
@optional
-(void)statusBarStateProvider:(id)provider didChangeDoubleHeightStatusStringForStyle:(int)style;
@end

